# Generated by Django 3.1.7 on 2021-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0002_userservice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
