# Generated by Django 3.1.7 on 2021-02-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0003_auto_20210223_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='importance',
            field=models.BooleanField(default=False),
        ),
    ]
