# Generated by Django 3.1.7 on 2021-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_app', '0004_service_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
